export type Tool = 'pencil' | 'eraser' | 'fill' | 'line' | 'rectangle' | 'select';
export type Variation = 'regular' | 'bold' | 'italic' | 'boldItalic'
export const variations: Record<Variation, string> = {
    regular: "Standard",
    bold: "Bold",
    italic: "Italic",
    boldItalic: "Bold Italic"
}

// WHY MUST I DO THIS BY HAND AHHHHH
// nvm i can copy paste ts 
export const googleFontsCatalog = [
  'Abril Fatface',
  'Alegreya',
  'Alegreya Sans',
  'Alex Brush',
  'Alfa Slab One',
  'Allura',
  'Amatic SC',
  'Anonymous Pro',
  'Anton',
  'Archivo',
  'Archivo Black',
  'Archivo Narrow',
  'Arimo',
  'Arsenal',
  'Arvo',
  'Asap',
  'Assistant',
  'Audiowide',
  'Bai Jamjuree',
  'Baloo 2',
  'Bangers',
  'Barlow',
  'Barlow Condensed',
  'Barlow Semi Condensed',
  'Baskervville',
  'Bebas Neue',
  'Belleza',
  'Bevan',
  'BioRhyme',
  'Bitter',
  'Bree Serif',
  'Bungee',
  'Bungee Inline',
  'Bungee Shade',
  'Cabin',
  'Cabin Condensed',
  'Candal',
  'Cardo',
  'Catamaran',
  'Caveat',
  'Chakra Petch',
  'Chewy',
  'Chivo',
  'Cinzel',
  'Cinzel Decorative',
  'Comfortaa',
  'Concert One',
  'Cookie',
  'Corben',
  'Cormorant',
  'Cormorant Garamond',
  'Courgette',
  'Cousine',
  'Crimson Pro',
  'Crimson Text',
  'Cutive Mono',
  'Dancing Script',
  'Days One',
  'DM Mono',
  'DM Sans',
  'DM Serif Display',
  'DM Serif Text',
  'Domine',
  'Dosis',
  'EB Garamond',
  'Eczar',
  'Encode Sans',
  'Epilogue',
  'Exo',
  'Exo 2',
  'Figtree',
  'Fira Code',
  'Fira Mono',
  'Fira Sans',
  'Fira Sans Condensed',
  'Fjalla One',
  'Frank Ruhl Libre',
  'Fraunces',
  'Fredoka',
  'Gelasio',
  'Glegoo',
  'Gochi Hand',
  'Grandstander',
  'Great Vibes',
  'Handlee',
  'Hanken Grotesk',
  'Heebo',
  'Hepta Slab',
  'Homemade Apple',
  'IBM Plex Mono',
  'IBM Plex Sans',
  'IBM Plex Sans Condensed',
  'IBM Plex Serif',
  'Ibarra Real Nova',
  'Inconsolata',
  'Indie Flower',
  'Inter',
  'Instrument Sans',
  'Instrument Serif',
  'Italiana',
  'JetBrains Mono',
  'Josefin Sans',
  'Josefin Slab',
  'Jost',
  'Julius Sans One',
  'Jura',
  'Kalam',
  'Kanit',
  'Karla',
  'Khand',
  'Kreon',
  'Krona One',
  'Kumbh Sans',
  'League Spartan',
  'Lekton',
  'Lemonada',
  'Lexend',
  'Libre Baskerville',
  'Libre Franklin',
  'Lilita One',
  'Literata',
  'Livvic',
  'Lobster',
  'Lora',
  'Lusitana',
  'Lustria',
  'Macondo',
  'Major Mono Display',
  'Manrope',
  'Marcellus',
  'Marck Script',
  'Markazi Text',
  'Martian Mono',
  'Maven Pro',
  'Merienda',
  'Merriweather',
  'Michroma',
  'Miriam Libre',
  'Modak',
  'Monoton',
  'Montaga',
  'Montserrat',
  'Mukta',
  'Mulish',
  'Neucha',
  'Neuton',
  'Newsreader',
  'Niconne',
  'Nixie One',
  'Nobile',
  'Norican',
  'Noticia Text',
  'Noto Sans',
  'Noto Serif',
  'Nova Mono',
  'Nunito',
  'Nunito Sans',
  'Offside',
  'Old Standard TT',
  'Oleo Script',
  'Open Sans',
  'Orbitron',
  'Oregano',
  'Original Surfer',
  'Oswald',
  'Outfit',
  'Overlock',
  'Overpass',
  'Overpass Mono',
  'Oxygen',
  'Pacifico',
  'Parisienne',
  'Passion One',
  'Patrick Hand',
  'Paytone One',
  'Permanent Marker',
  'Petrona',
  'Philosopher',
  'Piazzolla',
  'Pinyon Script',
  'Playfair Display',
  'Playfair Display SC',
  'Plus Jakarta Sans',
  'Poly',
  'Pontano Sans',
  'Poppins',
  'Press Start 2P',
  'Prompt',
  'Proza Libre',
  'PT Mono',
  'PT Sans',
  'PT Serif',
  'Public Sans',
  'Quantico',
  'Quattrocento',
  'Quattrocento Sans',
  'Questrial',
  'Quicksand',
  'Racing Sans One',
  'Radley',
  'Rajdhani',
  'Raleway',
  'Rambla',
  'Rammetto One',
  'Ranchers',
  'Readex Pro',
  'Red Hat Display',
  'Red Hat Mono',
  'Red Hat Text',
  'Righteous',
  'Roboto',
  'Roboto Condensed',
  'Roboto Mono',
  'Rock Salt',
  'Rokkitt',
  'Rosario',
  'Rubik',
  'Rubik Mono One',
  'Ruda',
  'Rufina',
  'Sacramento',
  'Sail',
  'Sanchez',
  'Sansita',
  'Sarala',
  'Satisfy',
  'Schoolbell',
  'Sedgwick Ave',
  'Sen',
  'Seymour One',
  'Shadows Into Light',
  'Signika',
  'Signika Negative',
  'Silkscreen',
  'Simonetta',
  'Six Caps',
  'Solway',
  'Sonsie One',
  'Sora',
  'Source Code Pro',
  'Source Sans 3',
  'Source Serif 4',
  'Space Grotesk',
  'Space Mono',
  'Spectral',
  'Special Elite',
  'Spinnaker',
  'Spline Sans Mono',
  'Squada One',
  'Staatliches',
  'Suez One',
  'Syncopate',
  'Tangerine',
  'Teko',
  'Tenor Sans',
  'Text Me One',
  'Tienne',
  'Tinos',
  'Titillium Web',
  'Trocchi',
  'Trykker',
  'Ubuntu',
  'Ubuntu Condensed',
  'Ubuntu Mono',
  'Unica One',
  'Unna',
  'Urbanist',
  'Varela Round',
  'Vast Shadow',
  'Vesper Libre',
  'Viga',
  'Vollkorn',
  'VT323',
  'Waiting for the Sunrise',
  'Wallpoet',
  'Wire One',
  'Work Sans',
  'Yanone Kaffeesatz',
  'Yellowtail',
  'Yeseva One',
  'Zeyada',
  'Zilla Slab',
];

const baseUC = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')

// this part was done manually actually help me atp
const accentUC = ['À', 'Á', 'Â', 'Ä', 'Ǎ', 'Æ', 'Ã', 'Å', 'Ā',
    'Ç', 'Ć', 'Č', 'Ċ', 'Ď', 'Ð',
    'È', 'É', 'Ê', 'Ë', 'Ě', 'Ẽ', 'Ē', 'Ė', 'Ę',
// it was at this point, when I lost my will to live.
// thank god for mac keyboards
    'Ğ', 'Ġ', 'Ħ', 'Ì', 'Í', 'Î', 'Ï', "Ǐ", 'Ĩ', 'Ī', 'Ī', 'Į', 'İ',
    'Ķ', 'Ł', "Ļ", 'Ľ', 'Ñ', 'Ń', 'Ņ', 'Ň', 'Ò', "Ó", 'Ô', 'Ö', "Ǒ", 'Œ', 'Ø', 'Õ', 'Ō',
    'Ř', 'ẞ', 'Ś', 'Š', 'Ş', 'Ș', 'Ț', "Ť", 'Þ', 'Ù', 'Ú', 'Û', 'Ü', 'Ǔ', 'Ũ', 'Ū', 'Ű', 'Ů',
    'Ŵ', 'Ý', 'Ŷ', 'Ÿ', 'Ź', 'Ž', 'Ż'
]

export const pairingLatin = [...baseUC, ...accentUC].flatMap((letter) => [letter, letter.toLowerCase()])
export const basePairLatin = baseUC.flatMap((letter) => [letter, letter.toLowerCase()])
export const digitChars = ['0', '2', '1', '3', '4', '5', '6', '7', '8', '9']
export const punctuationChars = ['.', ',', '!', '?', '@', '#', '&', '~', '^', '-', '_', ':', ';', "'", '"', '(', ')', '[', ']', '{', '}', '/', '\\', '|', '=', '*', '%', '$', '<', '>']
export const unpairedChars= [...digitChars, ...punctuationChars]
export const chars =[...pairingLatin, ...unpairedChars]
export const typefaces = [
    'Menlo, monospace',
    'Monaco, monospace', 'Consolas, monospace', "'Courier New', monospace",
    '"Lucida Console", monospace', "'Andale Mono', monospace"
]