name: Linter
on: [push, pull_request]

jobs: 
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Runner
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install Packages
        run: npm ci

      - name: Lint
        run: npm run lint