name: Linter
on: [push, pull_request]

jobs: 
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: actions/checkout@v4

        uses: actions/setup-node@v4
        with:
          node-cache: 'npm'
          
      - name: Install Packages
        run: npm ci

      - name: Lint
        run: npm eslint .